#pragma once
#include <glfw3.h>

#define ENJIN_KEY_UP GLFW_KEY_UP
#define ENJIN_KEY_DOWN GLFW_KEY_DOWN
#define ENJIN_KEY_RIGHT GLFW_KEY_RIGHT
#define ENJIN_KEY_LEFT GLFW_KEY_LEFT
#define ENJIN_KEY_W GLFW_KEY_W
#define ENJIN_KEY_S GLFW_KEY_S
#define ENJIN_KEY_D GLFW_KEY_D
#define ENJIN_KEY_A GLFW_KEY_A
#define ENJIN_KEY_Z GLFW_KEY_Z
#define ENJIN_KEY_X GLFW_KEY_X
#define ENJIN_KEY_SPACE GLFW_KEY_SPACE
#define ENJIN_KEY_ENTER GLFW_KEY_ENTER
#define ENJIN_KEY_ESCAPE GLFW_KEY_ESCAPE
#define ENJIN_MOUSE_BTN_LEFT GLFW_MOUSE_BUTTON_LEFT
#define ENJIN_MOUSE_BTN_RIGHT GLFW_MOUSE_BUTTON_RIGHT
#define ENJIN_MOUSE_BTN_MIDDLE GLFW_MOUSE_BUTTON_MIDDLE